# 00. TensorFlow Fundamentals Exercises

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [1]:
import tensorflow as tf

tf.__version__

'2.17.0'

In [2]:
scalar = tf.constant(2)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [3]:
vector = tf.constant([1,2,3])
vector

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 2, 3], dtype=int32)>

In [4]:
matrix = tf.constant([[1,2,3], [4,5,6]])
matrix

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [5]:
tensor = tf.constant([
    [
        [1,2,3],
        [4,5,6],
    ], [
        [4,5,6],
        [7,8,9],
    ]
])
tensor

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[1, 2, 3],
        [4, 5, 6]],

       [[4, 5, 6],
        [7, 8, 9]]], dtype=int32)>

# 00. TensorFlow Fundamentals Exercises
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.*